
tasks:
  - name: Terminal
    init: |
      curl -L -o score-compose.tgz https://github.com/score-spec/score-compose/releases/download/0.15.4/score-compose_0.15.4_linux_amd64.tar.gz
      tar xvzf score-compose.tgz score-compose
      rm score-compose.tgz
    command: |
      ./score-compose init --no-sample
      ./score-compose generate vote/score.yaml --build main=./vote
      ./score-compose generate worker/score.yaml --build main=./worker
      ./score-compose generate result/score.yaml --build main=./result
      ./score-compose generate seed-data/score.yaml --build main=./seed-data
      docker compose up -f compose.yaml -f extra-compose.yaml --attach-dependencies vote-main worker-main result-main

  - name: Wait for port
    command: |
      printf "Waiting for Voting App at $(gp url 5000) ..."
      gp ports await 5000
      gp open vote/app.py
    openMode: split-right

ports:
  - port: 5000
    onOpen: open-preview
  - port: 5001  # results
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python
