
tasks:
  - name: Terminal
    init: |
      curl -L -o score-compose.tgz https://github.com/score-spec/score-compose/releases/download/0.15.4/score-compose_0.15.4_linux_amd64.tar.gz
      tar xvzf score-compose.tgz score-compose
      rm score-compose.tgz
    command: |
      ./score-compose init --no-sample
      ./score-compose generate vote/score.yaml --build main=./vote
      ./score-compose generate worker/score.yaml --build main=./worker
      ./score-compose generate result/score.yaml --build main=./result
      docker compose -f compose.yaml up

  - name: Wait for port
    command: |
      printf "Waiting for Voting App at $(gp url 8080) ..."
      gp ports await 8080
    openMode: split-right

ports:
  - port: 8080
    onOpen: open-preview
  - port: 5001  # results
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python
