# Development only mixins for the compose file output by score-compose
services:
  vote-main:
    volumes:
     - ./vote:/usr/local/app
    ports:
      - "5000:80"
  result-main:
    volumes:
      - ./result:/usr/local/app
    ports:
      - "5001:80"
      - "127.0.0.1:9229:9229"
  # this service runs once to seed the database with votes
  # it won't run unless you specify the "seed" profile
  # docker compose -f compose.yaml -f extra-compose.yaml --profile seed up -d
  seed:
    profiles: ["seed"]
    restart: "no"
